# Generated by Django 5.2.4 on 2025-12-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('Medium', 'Medium'), ('High', 'High'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_orders', to='setup.customer')),
            ],
            options={
                'db_table': 'job_orders',
            },
        ),
        migrations.CreateModel(
            name='CoreTransaction',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('output_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_output', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qc_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.operator')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.joborder')),
            ],
            options={
                'db_table': 'trans_core',
            },
        ),
        migrations.CreateModel(
            name='JobOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.item')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.joborder')),
            ],
            options={
                'db_table': 'job_order_items',
            },
        ),
        migrations.CreateModel(
            name='LaminationTransaction',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plain_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('printed_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('laminated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_output', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qc_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.joborder')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.operator')),
            ],
            options={
                'db_table': 'trans_lamination',
            },
        ),
        migrations.CreateModel(
            name='PrintingTransaction',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('input_mat_kg', models.DecimalField(decimal_places=2, default=0, help_text='Input Material Kg', max_digits=10)),
                ('printed_kg', models.DecimalField(decimal_places=2, default=0, help_text='Printed Kg', max_digits=10)),
                ('wastage_kg', models.DecimalField(decimal_places=2, default=0, help_text='Wastage Kg', max_digits=10)),
                ('total_output_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.joborder')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.operator')),
            ],
            options={
                'db_table': 'trans_printing',
            },
        ),
        migrations.CreateModel(
            name='RewindingTransaction',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('output_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_output', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qc_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.joborder')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.operator')),
            ],
            options={
                'db_table': 'trans_rewinding',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_po_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='setup.customer')),
            ],
            options={
                'db_table': 'sales_orders',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.salesorder')),
            ],
            options={
                'db_table': 'sales_order_lines',
            },
        ),
        migrations.CreateModel(
            name='SlittingTransaction',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_width', models.DecimalField(decimal_places=2, default=0, help_text='Target Width (mm)', max_digits=10)),
                ('output_pcs', models.IntegerField(default=0)),
                ('waste_weight', models.DecimalField(decimal_places=2, default=0, help_text='Trim/Waste (Kg)', max_digits=10)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.joborder')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.operator')),
            ],
            options={
                'db_table': 'trans_slitting',
            },
        ),
    ]
