# Generated by Django 5.2.4 on 2025-12-13 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_item_gsm_item_thickness_item_width_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printingtransaction',
            options={'verbose_name': 'Printing Transaction'},
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='customer',
        ),
        migrations.AddField(
            model_name='joborder',
            name='sales_order',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='job_orders', to='transactions.salesorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coretransaction',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.joborder'),
        ),
        migrations.AlterField(
            model_name='laminationtransaction',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.joborder'),
        ),
        migrations.AlterField(
            model_name='printingtransaction',
            name='input_mat_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='printingtransaction',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.joborder'),
        ),
        migrations.AlterField(
            model_name='printingtransaction',
            name='printed_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='printingtransaction',
            name='wastage_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewindingtransaction',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.joborder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='setup.customer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('In Production', 'In Production'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='slittingtransaction',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.joborder'),
        ),
    ]
