# Generated by Django 5.2.4 on 2025-12-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gsm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in GSM', max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='thickness',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Thickness in microns', max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Width in mm', max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='max_width_capacity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max width (mm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='speed_capacity',
            field=models.IntegerField(default=0, help_text='Speed capacity (e.g. m/min)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('maintenance', 'On Maintenance')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('local', 'Local'), ('export', 'Export'), ('pharma', 'Pharma'), ('individual', 'Individual'), ('business', 'Business'), ('government', 'Government')], default='business', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Official registered name', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='specifications',
            field=models.TextField(blank=True, help_text='Other specifics', null=True),
        ),
    ]
