# Generated by Django 5.2.4 on 2025-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_item_gsm_item_thickness_item_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
