from django.db import models

# Helper for common field options to allow easy import
NULLABLE = {'blank': True, 'null': True}

class SLTransactionProduction(models.Model):
    ucode = models.CharField(max_length=100, **NULLABLE)
    posted = models.CharField(max_length=10, **NULLABLE)
    doc_locked = models.CharField(max_length=10, **NULLABLE)
    system_code = models.CharField(max_length=100, **NULLABLE)
    trans_number = models.CharField(max_length=100, **NULLABLE)
    trans_date = models.DateField(**NULLABLE)
    shift_code = models.CharField(max_length=50, **NULLABLE)
    trans_type = models.CharField(max_length=50, **NULLABLE)
    job_no = models.CharField(max_length=100, **NULLABLE)
    product_code = models.CharField(max_length=100, **NULLABLE)
    machine_code = models.CharField(max_length=100, **NULLABLE)
    machine_operator = models.CharField(max_length=255, **NULLABLE)
    assistant = models.CharField(max_length=255, **NULLABLE)
    helper = models.CharField(max_length=255, **NULLABLE)
    temperature = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rubber_size = models.CharField(max_length=100, **NULLABLE)
    speed = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    blade = models.CharField(max_length=100, **NULLABLE)
    lamination_no = models.CharField(max_length=100, **NULLABLE)
    remarks = models.TextField(**NULLABLE)
    meters = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    glue = models.CharField(max_length=100, **NULLABLE)
    glue_weight = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    hardner_weight = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    resin = models.CharField(max_length=100, **NULLABLE)
    solvent = models.CharField(max_length=100, **NULLABLE)
    bf_weight1 = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bf_weight2 = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    af_weight = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bf_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    af_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    machine_trim = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    treatment = models.CharField(max_length=100, **NULLABLE)
    start_date = models.DateField(**NULLABLE)
    start_time = models.CharField(max_length=50, **NULLABLE) # Time sometimes comes as string
    start_done = models.CharField(max_length=10, **NULLABLE)
    end_date = models.DateField(**NULLABLE)
    end_time = models.CharField(max_length=50, **NULLABLE)
    end_done = models.CharField(max_length=10, **NULLABLE)
    created_by = models.CharField(max_length=100, **NULLABLE)
    created_date = models.DateTimeField(**NULLABLE)
    maintained_by = models.CharField(max_length=100, **NULLABLE)
    maintained_date = models.DateTimeField(**NULLABLE)
    workstation = models.CharField(max_length=100, **NULLABLE)
    qc_hold = models.CharField(max_length=10, **NULLABLE)
    glue_name = models.CharField(max_length=255, **NULLABLE)
    glue_type = models.CharField(max_length=100, **NULLABLE)
    hardner = models.CharField(max_length=100, **NULLABLE)
    sliting_width = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    sliting_cutting = models.CharField(max_length=100, **NULLABLE)
    sliting_direction = models.CharField(max_length=100, **NULLABLE)
    final_farword_wt = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    last_station_wt = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ethyle = models.CharField(max_length=100, **NULLABLE)
    used_glue = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    printing_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    solvent_used = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    solvent_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ink_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    glue_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    hardner_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ethyl_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    trim_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    mc_trouble_shooting_mint = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    average_speed = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    total_production_minute = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    txt_balance_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    maintenance_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    proofing_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    litedark_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ethyle_name = models.CharField(max_length=255, **NULLABLE)
    repeat_job = models.CharField(max_length=10, **NULLABLE)
    selfparty_approval = models.CharField(max_length=100, **NULLABLE)
    proofings = models.CharField(max_length=100, **NULLABLE)
    qc_release = models.CharField(max_length=10, **NULLABLE)
    qc_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    qc_remarks = models.TextField(**NULLABLE)
    prd_remarks = models.TextField(**NULLABLE)
    d_type = models.CharField(max_length=50, **NULLABLE)
    d_no = models.CharField(max_length=50, **NULLABLE)
    d_date = models.DateField(**NULLABLE)
    machine_operator2 = models.CharField(max_length=255, **NULLABLE)
    supervisor = models.CharField(max_length=255, **NULLABLE)
    bal_plain_weight = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bal_printed_weight = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    printing_mcode = models.CharField(max_length=100, **NULLABLE)
    printing_mtitle = models.CharField(max_length=255, **NULLABLE)
    no_of_color = models.IntegerField(**NULLABLE)
    position = models.CharField(max_length=100, **NULLABLE)
    printing_file_no = models.CharField(max_length=100, **NULLABLE)
    black_lineside = models.CharField(max_length=100, **NULLABLE)
    unwind_direction = models.CharField(max_length=100, **NULLABLE)
    quality_checker = models.CharField(max_length=255, **NULLABLE)
    color_macher = models.CharField(max_length=255, **NULLABLE)
    dry_gsm = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    issue_date = models.DateField(**NULLABLE)

class SLSaleOrderMaster(models.Model):
    ucode = models.CharField(max_length=100, **NULLABLE)
    posted = models.CharField(max_length=10, **NULLABLE)
    doc_locked = models.CharField(max_length=10, **NULLABLE)
    guid = models.CharField(max_length=255, **NULLABLE)
    audit = models.CharField(max_length=255, **NULLABLE)
    trans_year = models.CharField(max_length=10, **NULLABLE)
    system_code = models.CharField(max_length=100, **NULLABLE)
    po_n = models.CharField(max_length=100, **NULLABLE)
    trans_number = models.CharField(max_length=100, **NULLABLE)
    trans_date = models.DateField(**NULLABLE)
    trans_date2 = models.DateField(**NULLABLE)
    shift_code = models.CharField(max_length=50, **NULLABLE)
    trans_type = models.CharField(max_length=50, **NULLABLE)
    sarea_code = models.CharField(max_length=50, **NULLABLE)
    rarea_code = models.CharField(max_length=50, **NULLABLE)
    nature = models.CharField(max_length=100, **NULLABLE)
    charging_area = models.CharField(max_length=100, **NULLABLE)
    cost_center = models.CharField(max_length=100, **NULLABLE)
    supplier_code = models.CharField(max_length=100, **NULLABLE)
    remarks = models.TextField(**NULLABLE)
    conditions = models.TextField(**NULLABLE)
    nature_code = models.CharField(max_length=50, **NULLABLE)
    category_code = models.CharField(max_length=50, **NULLABLE)
    dispatch_type = models.CharField(max_length=50, **NULLABLE)
    dispatch_time = models.CharField(max_length=50, **NULLABLE)
    credit_days = models.IntegerField(**NULLABLE)
    po_number = models.CharField(max_length=100, **NULLABLE)
    po_date = models.DateField(**NULLABLE)
    dc_number = models.CharField(max_length=100, **NULLABLE)
    dc_date = models.DateField(**NULLABLE)
    prd_number = models.CharField(max_length=100, **NULLABLE)
    prd_date = models.DateField(**NULLABLE)
    req_slip_number = models.CharField(max_length=100, **NULLABLE)
    req_slip_date = models.DateField(**NULLABLE)
    grir_number = models.CharField(max_length=100, **NULLABLE)
    grir_date = models.DateField(**NULLABLE)
    bill_number = models.CharField(max_length=100, **NULLABLE)
    bill_date = models.DateField(**NULLABLE)
    sti_number = models.CharField(max_length=100, **NULLABLE)
    sti_date = models.DateField(**NULLABLE)
    ar_clearance = models.CharField(max_length=10, **NULLABLE)
    customer_code = models.CharField(max_length=100, **NULLABLE)
    fox_code = models.CharField(max_length=100, **NULLABLE)
    cus_client_code = models.CharField(max_length=100, **NULLABLE)
    plan_number = models.CharField(max_length=100, **NULLABLE)
    plan_date = models.DateField(**NULLABLE)
    da_number = models.CharField(max_length=100, **NULLABLE)
    da_date = models.DateField(**NULLABLE)
    billty_number = models.CharField(max_length=100, **NULLABLE)
    billty_date = models.DateField(**NULLABLE)
    freight_amt = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    other_amt = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    trans_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    filled_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    gl_locked = models.CharField(max_length=10, **NULLABLE)
    rp_filled_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rp_locked = models.CharField(max_length=10, **NULLABLE)
    pdate = models.DateField(**NULLABLE)
    invoice_number = models.CharField(max_length=100, **NULLABLE)
    ref_no = models.CharField(max_length=100, **NULLABLE)
    reference = models.CharField(max_length=255, **NULLABLE)
    delivery_a = models.CharField(max_length=255, **NULLABLE)
    delivery_at = models.CharField(max_length=255, **NULLABLE)
    delivery_t = models.CharField(max_length=255, **NULLABLE)
    delivery_to = models.CharField(max_length=255, **NULLABLE)
    delivery_time = models.CharField(max_length=50, **NULLABLE)
    trade_discount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    customer_closing = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    salesman_code = models.CharField(max_length=100, **NULLABLE)
    currency_code = models.CharField(max_length=50, **NULLABLE)
    customer_discount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    vat = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    sale_tax = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    loc = models.CharField(max_length=50, **NULLABLE)
    create_date = models.DateField(**NULLABLE)
    create_time = models.CharField(max_length=50, **NULLABLE)
    modified_date = models.DateField(**NULLABLE)
    modified_time = models.CharField(max_length=50, **NULLABLE)
    oc_category = models.CharField(max_length=100, **NULLABLE)
    deal_no = models.CharField(max_length=100, **NULLABLE)
    deal_size = models.CharField(max_length=100, **NULLABLE)
    oc_blocked = models.CharField(max_length=10, **NULLABLE)
    created_by = models.CharField(max_length=100, **NULLABLE)
    created_date = models.DateTimeField(**NULLABLE)
    maintained_by = models.CharField(max_length=100, **NULLABLE)
    maintained_date = models.DateTimeField(**NULLABLE)
    workstation = models.CharField(max_length=100, **NULLABLE)
    log_chk = models.CharField(max_length=10, **NULLABLE)
    foc_chk = models.CharField(max_length=10, **NULLABLE)
    zrno = models.CharField(max_length=100, **NULLABLE)
    oc_type = models.CharField(max_length=50, **NULLABLE)
    approved_by2 = models.CharField(max_length=100, **NULLABLE)
    approved_date2 = models.DateField(**NULLABLE)
    approved_by_time = models.CharField(max_length=50, **NULLABLE)

class SLSaleOrderDetail(models.Model):
    system_code = models.CharField(max_length=100, **NULLABLE)
    trans_number = models.CharField(max_length=100, **NULLABLE)
    trans_date = models.DateField(**NULLABLE)
    trans_type = models.CharField(max_length=50, **NULLABLE)
    ucode = models.CharField(max_length=100, **NULLABLE)
    snum = models.CharField(max_length=100, **NULLABLE)
    srn_number = models.CharField(max_length=100, **NULLABLE)
    srn_type = models.CharField(max_length=50, **NULLABLE)
    po_number = models.CharField(max_length=100, **NULLABLE)
    i = models.CharField(max_length=100, **NULLABLE)
    item_code = models.CharField(max_length=100, **NULLABLE)
    item_locked = models.CharField(max_length=10, **NULLABLE)
    item_status = models.CharField(max_length=50, **NULLABLE)
    add_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    filled_quantity = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    billed_quantity = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rcp_quantity = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    iss_quantity = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    pcs_quantity = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    meter_quantity = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rcp_price = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    iss_price = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rcp_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    iss_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    pack_contains = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    kg_contains = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    packing = models.CharField(max_length=100, **NULLABLE)
    rate_ed_inv = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    value_ed_inv = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rate_std_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    value_std_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rate_nsales = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    value_nsales = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    sale_price = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_percent = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_percent_a = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ed_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ed_value = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ed_percent = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ed_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    freight_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ot_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    avg_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    avg_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    receipt_code = models.CharField(max_length=100, **NULLABLE)
    issue_code = models.CharField(max_length=100, **NULLABLE)
    wip_code = models.CharField(max_length=100, **NULLABLE)
    cogs_code = models.CharField(max_length=100, **NULLABLE)
    sales_tax_code = models.CharField(max_length=100, **NULLABLE)
    excise_code = models.CharField(max_length=100, **NULLABLE)
    sale_code = models.CharField(max_length=100, **NULLABLE)
    process_code = models.CharField(max_length=100, **NULLABLE)
    freight_code = models.CharField(max_length=100, **NULLABLE)
    other_code = models.CharField(max_length=100, **NULLABLE)
    up_bill_code = models.CharField(max_length=100, **NULLABLE)
    u_std_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    u_stdr_process = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    scheme_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    scheme_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    scheme_gross_total = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    scheme_trans_number = models.CharField(max_length=100, **NULLABLE)
    contain = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    forex_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    forex_amount = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    calc_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    qty_used = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    oqty_used = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    schedule_date = models.DateField(**NULLABLE)
    schedule_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    backlog = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    current_dp = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    hold = models.CharField(max_length=10, **NULLABLE)
    usd = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ojob_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    status = models.CharField(max_length=50, **NULLABLE)
    deal_no_dt = models.CharField(max_length=100, **NULLABLE)
    dealsize_dt = models.CharField(max_length=100, **NULLABLE)
    log_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    printed_type = models.CharField(max_length=100, **NULLABLE)
    deal_price = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    zrno = models.CharField(max_length=100, **NULLABLE)

class SLOperator(models.Model):
    code = models.CharField(max_length=100, **NULLABLE)
    title = models.CharField(max_length=255, **NULLABLE)
    designation = models.CharField(max_length=255, **NULLABLE)
    t1 = models.CharField(max_length=50, **NULLABLE)
    t2 = models.CharField(max_length=50, **NULLABLE)
    designation1 = models.CharField(max_length=255, **NULLABLE)
    ucode = models.CharField(max_length=100, **NULLABLE)

class SLJobMaster(models.Model):
    zrno = models.CharField(max_length=100, **NULLABLE)
    system_code = models.CharField(max_length=100, **NULLABLE)
    ucode = models.CharField(max_length=100, **NULLABLE)
    job_no = models.CharField(max_length=100, **NULLABLE)
    job_date = models.DateField(**NULLABLE)
    job_status = models.CharField(max_length=50, **NULLABLE)
    job_completion_date = models.DateField(**NULLABLE)
    job_unsettle = models.CharField(max_length=10, **NULLABLE)
    i = models.CharField(max_length=100, **NULLABLE)
    item_code = models.CharField(max_length=100, **NULLABLE)
    job_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    from_date = models.DateField(**NULLABLE)
    to_date = models.DateField(**NULLABLE)
    remarks = models.TextField(**NULLABLE)
    cs_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rec_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    category = models.CharField(max_length=100, **NULLABLE)
    create_date = models.DateField(**NULLABLE)
    create_time = models.CharField(max_length=50, **NULLABLE)
    modified_date = models.DateField(**NULLABLE)
    modified_time = models.CharField(max_length=50, **NULLABLE)
    created_by = models.CharField(max_length=100, **NULLABLE)
    created_date = models.DateTimeField(**NULLABLE)
    maintained_by = models.CharField(max_length=100, **NULLABLE)
    maintained_date = models.DateTimeField(**NULLABLE)
    workstation = models.CharField(max_length=100, **NULLABLE)
    posted = models.CharField(max_length=10, **NULLABLE)
    wastage_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ups = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ptrim = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    film_size = models.CharField(max_length=100, **NULLABLE)
    pup_size = models.CharField(max_length=100, **NULLABLE)
    ink_remarks = models.TextField(**NULLABLE)
    job_pcs_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    transport_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    labour = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bag_making_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    zipper_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    cylinder_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    gussed_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    time_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    last_process = models.CharField(max_length=100, **NULLABLE)
    print_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    rewind_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    lam_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    slit_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    print_mat = models.CharField(max_length=100, **NULLABLE)
    lam_mat1 = models.CharField(max_length=100, **NULLABLE)
    lam_mat2 = models.CharField(max_length=100, **NULLABLE)
    rate_apply = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    j_trim = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    j_wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    oc_no = models.CharField(max_length=100, **NULLABLE)

class SLItem(models.Model):
    item_code = models.CharField(max_length=100, **NULLABLE)
    item = models.CharField(max_length=255, **NULLABLE)
    i1 = models.CharField(max_length=100, **NULLABLE)
    item_type = models.CharField(max_length=100, **NULLABLE)
    item_detail = models.CharField(max_length=255, **NULLABLE)
    item_category = models.CharField(max_length=100, **NULLABLE)
    system_code = models.CharField(max_length=100, **NULLABLE)
    un_active = models.CharField(max_length=10, **NULLABLE)
    sp = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    item_specification = models.CharField(max_length=255, **NULLABLE)
    plies = models.IntegerField(**NULLABLE)
    plies_rough = models.CharField(max_length=100, **NULLABLE)
    plant = models.CharField(max_length=100, **NULLABLE)
    cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    price = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    sheets = models.IntegerField(**NULLABLE)
    grams = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    cutting = models.CharField(max_length=100, **NULLABLE)
    heigth = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    width = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bursting = models.CharField(max_length=100, **NULLABLE)
    gramage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    moisture = models.CharField(max_length=50, **NULLABLE)
    top_crush = models.CharField(max_length=50, **NULLABLE)
    edge_crush = models.CharField(max_length=50, **NULLABLE)
    cwc_size = models.CharField(max_length=50, **NULLABLE)
    e = models.CharField(max_length=50, **NULLABLE)
    partition_size = models.CharField(max_length=50, **NULLABLE)
    sale_unit = models.CharField(max_length=50, **NULLABLE)
    t_u = models.CharField(max_length=50, **NULLABLE)
    item_unit = models.CharField(max_length=50, **NULLABLE)
    base_item = models.CharField(max_length=100, **NULLABLE)
    customer_code = models.CharField(max_length=100, **NULLABLE)
    kg_contains = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ro_level = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ro_qty = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    cr_level = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    spare_part = models.CharField(max_length=10, **NULLABLE)
    equipment_ref = models.CharField(max_length=255, **NULLABLE)
    rack_number = models.CharField(max_length=50, **NULLABLE)
    bin_number = models.CharField(max_length=50, **NULLABLE)
    charging_area = models.CharField(max_length=100, **NULLABLE)
    reportable = models.CharField(max_length=10, **NULLABLE)
    active = models.CharField(max_length=10, **NULLABLE)
    wastage = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ex_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ex_per = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_rate = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_per = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    st_unit = models.CharField(max_length=50, **NULLABLE)
    st_category = models.CharField(max_length=50, **NULLABLE)
    ex_unit = models.CharField(max_length=50, **NULLABLE)
    contains_unit = models.CharField(max_length=50, **NULLABLE)
    issue_year1 = models.IntegerField(**NULLABLE)
    issue_year2 = models.IntegerField(**NULLABLE)
    issue_year3 = models.IntegerField(**NULLABLE)
    created_by = models.CharField(max_length=100, **NULLABLE)
    created_date = models.DateTimeField(**NULLABLE)
    maintained_by = models.CharField(max_length=100, **NULLABLE)
    maintained_date = models.DateTimeField(**NULLABLE)
    workstation = models.CharField(max_length=100, **NULLABLE)
    gl_code = models.CharField(max_length=100, **NULLABLE)
    usd_price = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    no_color = models.IntegerField(**NULLABLE)
    friction = models.CharField(max_length=50, **NULLABLE)
    alkali_resistance = models.CharField(max_length=50, **NULLABLE)
    sunlight = models.CharField(max_length=50, **NULLABLE)
    fr_height = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    fr_width = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    inner_core_dia = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    micron = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    wt_per_pcs = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    weight = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    nature = models.CharField(max_length=100, **NULLABLE)
    item_sub_category = models.CharField(max_length=100, **NULLABLE)
    supplier = models.CharField(max_length=100, **NULLABLE)
    item_group = models.CharField(max_length=100, **NULLABLE)
    cost_centre_code = models.CharField(max_length=100, **NULLABLE)
    perm_pcs_prmc = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    temp_pcs_prmc = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    temp_reason = models.CharField(max_length=255, **NULLABLE)
    kg_pr_pcs = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    created_on = models.DateTimeField(**NULLABLE)
    to_item = models.CharField(max_length=100, **NULLABLE)
    length = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    cutof_length = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    ups = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    z1 = models.CharField(max_length=100, **NULLABLE)
    as_per = models.CharField(max_length=255, **NULLABLE)
    type3 = models.CharField(max_length=100, **NULLABLE)
    cylinder = models.CharField(max_length=100, **NULLABLE)
    lamination_no = models.CharField(max_length=100, **NULLABLE)
    repeat_no = models.CharField(max_length=100, **NULLABLE)
    sliting_width = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    sliting_cutting = models.CharField(max_length=100, **NULLABLE)
    sliting_direction = models.CharField(max_length=100, **NULLABLE)
    ink_series = models.CharField(max_length=100, **NULLABLE)
    ink2 = models.CharField(max_length=100, **NULLABLE)
    bag_width = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bag_height = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bag_type = models.CharField(max_length=100, **NULLABLE)
    ink_series2 = models.CharField(max_length=100, **NULLABLE)
    up_size = models.CharField(max_length=100, **NULLABLE)
    ptrim = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    pdirection = models.CharField(max_length=100, **NULLABLE)
    glue_name = models.CharField(max_length=255, **NULLABLE)
    glue_type = models.CharField(max_length=100, **NULLABLE)
    hardner = models.CharField(max_length=100, **NULLABLE)
    alternate_item = models.CharField(max_length=100, **NULLABLE)
    client_material_code = models.CharField(max_length=100, **NULLABLE)
    bud_base = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bud_white = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bud_solvent = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bud_ink_solvent = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bud_base_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bud_white_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    bud_solvent_cost = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    pvt_item = models.CharField(max_length=10, **NULLABLE)

class SLInventoryMaster(models.Model):
    system_code = models.CharField(max_length=100, **NULLABLE)
    fox_code = models.CharField(max_length=100, **NULLABLE)
    master_code = models.CharField(max_length=100, **NULLABLE)
    master_name = models.CharField(max_length=255, **NULLABLE)
    receipt_code = models.CharField(max_length=100, **NULLABLE)
    issue_code = models.CharField(max_length=100, **NULLABLE)
    gst_code = models.CharField(max_length=100, **NULLABLE)
    exd_code = models.CharField(max_length=100, **NULLABLE)
    sale_code = models.CharField(max_length=100, **NULLABLE)
    process_code = models.CharField(max_length=100, **NULLABLE)
    wip_code = models.CharField(max_length=100, **NULLABLE)
    wips_code = models.CharField(max_length=100, **NULLABLE)
    cogs_code = models.CharField(max_length=100, **NULLABLE)
    other_code = models.CharField(max_length=100, **NULLABLE)
    up_bill_code = models.CharField(max_length=100, **NULLABLE)
    freight_code = models.CharField(max_length=100, **NULLABLE)
    ex_sale_code = models.CharField(max_length=100, **NULLABLE)

class SLCustomerMaster(models.Model):
    code = models.CharField(max_length=100, **NULLABLE)
    title = models.CharField(max_length=255, **NULLABLE)
    short_name = models.CharField(max_length=100, **NULLABLE)
    address = models.TextField(**NULLABLE)
    city = models.CharField(max_length=100, **NULLABLE)
    zone_code = models.CharField(max_length=100, **NULLABLE)
    zip_code = models.CharField(max_length=50, **NULLABLE)
    category = models.CharField(max_length=100, **NULLABLE)
    phone1 = models.CharField(max_length=50, **NULLABLE)
    phone2 = models.CharField(max_length=50, **NULLABLE)
    mobile = models.CharField(max_length=50, **NULLABLE)
    fax = models.CharField(max_length=50, **NULLABLE)
    email = models.CharField(max_length=255, **NULLABLE)
    web_address = models.CharField(max_length=255, **NULLABLE)
    territory_code = models.CharField(max_length=100, **NULLABLE)
    salesman_code = models.CharField(max_length=100, **NULLABLE)
    customer_group = models.CharField(max_length=100, **NULLABLE)
    gst_code = models.CharField(max_length=100, **NULLABLE)
    ntn_code = models.CharField(max_length=100, **NULLABLE)
    vat_percent = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    circle_code = models.CharField(max_length=100, **NULLABLE)
    au_person = models.CharField(max_length=255, **NULLABLE)
    au_designation = models.CharField(max_length=255, **NULLABLE)
    credit_days = models.IntegerField(**NULLABLE)
    credit_basis = models.CharField(max_length=50, **NULLABLE)
    bank_code = models.CharField(max_length=100, **NULLABLE)
    branch_code = models.CharField(max_length=100, **NULLABLE)
    account_number = models.CharField(max_length=100, **NULLABLE)
    status = models.CharField(max_length=50, **NULLABLE)
    schedule = models.CharField(max_length=255, **NULLABLE)
    hold = models.CharField(max_length=10, **NULLABLE)
    credit_limit = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    growth_target = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    created_by = models.CharField(max_length=100, **NULLABLE)
    created_date = models.DateTimeField(**NULLABLE)
    maintained_by = models.CharField(max_length=100, **NULLABLE)
    maintained_date = models.DateTimeField(**NULLABLE)
    workstation = models.CharField(max_length=100, **NULLABLE)
    commision = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    cnic = models.CharField(max_length=50, **NULLABLE)
    without_oc = models.CharField(max_length=10, **NULLABLE)
    eis_report = models.CharField(max_length=10, **NULLABLE)
    eis_ar = models.CharField(max_length=10, **NULLABLE)
    waste_per = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    income_tax = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    schedule_wise_stock = models.CharField(max_length=10, **NULLABLE)
    eis_ar_old = models.CharField(max_length=10, **NULLABLE)
    further_tax = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    further_tax_v = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    half_crtn_allow = models.CharField(max_length=10, **NULLABLE)
    sale_order_limit = models.DecimalField(max_digits=18, decimal_places=4, **NULLABLE)
    customer_type2 = models.CharField(max_length=50, **NULLABLE)
    designation_2 = models.CharField(max_length=255, **NULLABLE)
    un_active3 = models.CharField(max_length=10, **NULLABLE)
    address2 = models.TextField(**NULLABLE)
    address3 = models.TextField(**NULLABLE)
    address4 = models.TextField(**NULLABLE)
    code_pvt = models.CharField(max_length=100, **NULLABLE)

class SLArea(models.Model):
    area_code = models.CharField(max_length=100, **NULLABLE)
    area = models.CharField(max_length=255, **NULLABLE)
    system_code = models.CharField(max_length=100, **NULLABLE)
